### PR TITLE
Fixes, options, and tests added

### PR DESCRIPTION
**Pull request by chrisblossom**
I fixed the issue described in #6 and added unit tests, various options and because of all this a major refactor.

The {options} should gracefully fall back to the string context root, but it might be a good idea to version bump to 1.0.0 and follow semver from here on out.

Please let me know if you need me to change/update anything.

### CODE REVIEW

**Comment by hanjukim** [comment]
I also want this PR to be merged. Thank you.

**Comment by bakito** [comment]
+1

**Comment by chrisblossom** [comment]
@johnagan I added travis-ci and coveralls to the build too. You will have to sign up and enable your repo for the badges to work.

**Comment by morinted** [comment]
This is nice, but why is it 37 commits? Might be nice to have it rebased into something a little more cohesive.

**Comment by chrisblossom** [comment]
@morinted Thanks for the suggestion, definitely a big git learning experience for me. Everything is rebased into 6 commits now.

**Comment by chrisblossom** [comment]
@johnagan Is there something that needs to be changed for this PR to be merged? Please advise.

**Comment by johnagan** [comment]
Thanks folks! I'll get this merged in and published this weekend :sparkles:

**Comment by mikestopcontinues** [comment]
Can we get this one?

**Comment by johnagan** [comment]
Done! Thanks for the contributions! Hope this helps. :boom: 

https://www.npmjs.com/package/clean-webpack-plugin

**Comment by IngwiePhoenix** [comment]
This helps a lot! Thanks for having this merged. :)

**Comment by mikestopcontinues** [comment]
Thanks, man!

**Pull request merged**
