### PR TITLE
Proposed plugin revamp

### PR DESCRIPTION
**Pull request by chrisblossom**
[README.md](https://github.com/chrisblossom/clean-webpack-plugin/blob/2.0/README.md)

Changes:
- No configuration is needed for standard usage (cleans webpack's `output.path`)
- By default during webpack's watch mode, only files created by webpack are removed
- Because [del](https://www.npmjs.com/package/del) is used, globbing is supported
- Plugin is tested directly via webpack
- All supported versions are tested
- Windows is tested via [appveyor](https://www.appveyor.com/) (no mocked tests)
- Complete build system including prepublish hooks and git prepush/commit hooks
- Written with Typescript

Additional notes:
- Moved to [CircleCI](https://circleci.com/) because [Travis CI was sold](https://news.ycombinator.com/item?id=18978251) and [looks to now be in maintenance mode](https://news.ycombinator.com/item?id=19218036).
- Replaced Coveralls with [codecov](https://codecov.io/) because automatic build merging works. This is important because of windows/different webpack version testing

Please discuss the current API and suggest any changes.

Closes Issues: #53 #55 #67 #73 #80 #85 #86 #89 #91 #92 #93 #98 
Closes PRs: #39 #74

### CODE REVIEW

**Comment by johnagan** [comment]
This looks great! Thank you for putting in the work on this @chrisblossom 🎉
Should we merge this into master and push to npm?

**Comment by chrisblossom** [comment]
Yes I think we should. Should I change the version from `2.0.0-alpha1` to `2.0.0`?

Also, I'll need you to sign up and add to the github repo [circleci.com](https://circleci.com), [appveyor](https://www.appveyor.com) and [codecov.io](https://codecov.io). Let me know if you use a different username than `johnagan` for any of the services so I can update the readme links.

I think this should all be done before publishing to NPM.

**Comment by johnagan** [comment]
> add to the github repo circleci.com, appveyor and codecov.io. 
✅

**Comment by chrisblossom** [comment]
Thanks for getting that done!

With CircleCI, you'll want to turn on `Settings > Build Settings > Advanced Settings > Build forked pull requests`.

Do you want to release a `@next` `2.0.0-alpha1` version or go straight into `2.0.0`? I think releasing this as `2.0.0` will get the most/quickest feedback and since `del`'s force option is disabled by default, it will not remove any files outside of a project. Also their webpack config will throw an error because the API has completely changed.

**Comment by johnagan** [comment]
> With CircleCI, you'll want to turn on Settings > Build Settings > Advanced Settings > Build forked pull requests.

done!

Let's go with 2.0.0 and see how it goes

**Comment by chrisblossom** [comment]
Can you add me to the [AppVeyor team](https://ci.appveyor.com/team)? My username is chrisblossom, email cbloss@gmail.com. I just want to be able to re-run builds.

Looks like CircleCI already lets me because I'm a github collaborator for this repo. If you want help maintaining the npm version, my npm username is [chrisblossom](https://www.npmjs.com/~chrisblossom).

I'm going to go ahead and merge this in. Once you push to NPM, I'll close the issues/PRs I linked in this PR.

**Comment by stereokai** [comment]
Wow, that's *amazing*. Phenomenal!

**Pull request merged**
