### PR TITLE
WIP: Clean on fail

### LINKED ISSUE #179: delete build/* files at once(before build result)
### Issue description or question

i`d like to remove build output files when webpack build failed ,
 or remove  build output files when start building

like 
```bash
 rm -rf ./build  && webpack --progress --config webpack.config.js"
```

### Webpack Config

```js
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin'); // loader/plugins耗时分析
const { resolve } = require('path');
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');
const TerserPlugin = require('terser-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin'); //remove output
const WebpackBuildNotifierPlugin = require('webpack-build-notifier'); // build 
const WebpackShellPlugin = require('webpack-shell-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const smp = new SpeedMeasurePlugin();

const plugins = [
  new CleanWebpackPlugin({}),
  new WebpackShellPlugin({
    onBuildStart: ['echo "Starting build ... "'],
    onBuildEnd: ['echo "Webpack End"'],
  }),
  new WebpackBuildNotifierPlugin({
    title: 'xxx!',
    suppressSuccess: false,
    suppressCompileStart: false,
    suppressWarning: false,
    activateTerminalOnError: true,
  }),
  new ForkTsCheckerWebpackPlugin({
    typescript: false,
    async: true,
    eslint: {
      files: './src/**/*.ts',
      options: {
        fix: true,
      },
    },
  }),
];

if (process.env.npm_config_report) {
  plugins.push(new BundleAnalyzerPlugin());
}

/**
 * main
 */
module.exports = smp.wrap({
  mode: 'production',
  entry: {
    bdcharts: './src/index.ts',
  },
  devtool: 'source-map',
  output: {
    filename: 'bytecharts.js',
    path: resolve(__dirname, 'build'),
    library: 'Bytecharts',
    libraryTarget: 'umd',
    libraryExport: 'default',
    globalObject: 'this',
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              compiler: 'ttypescript',
            },
          },
        ],
        include: [resolve(__dirname, 'src')],
      },
      {
        test: /\.node$/,
        use: 'node-loader',
      },
    ],
  },
  plugins: plugins,
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
    alias: {
      '@src': resolve(__dirname, './src/'),
      '@map': resolve(__dirname, './map/'),
    },
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: {
            drop_console: true,
          },
        },
      }),
    ],
  },
  performance: {
    maxAssetSize: 500000,
  },
});

```

### Environment

Run: `npx envinfo --system --binaries --npmPackages clean-webpack-plugin,webpack`

```bash
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.21 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  npmPackages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    webpack: 4.42.0 => 4.42.0 
```

### PR DESCRIPTION
**Pull request by jneuendorf**
Fixes #179

### CODE REVIEW

**Comment by jneuendorf** [comment]
I need some help, because `test.all` fails (I had to disable `husky` in order to push anyway, create a PR and ask for help). 😕 

For some reason the tests don't pass for `webpack@next` but I have no idea why/how my code changes can cause that. Could any of you please have a look and give me a hint? Thanks in advance 🙂

**Comment by jneuendorf** [comment]
@chrisblossom You seem to most active contributor. Could you please take a look? Maybe you find a hint that leads me into the right direction, quickly. Thanks in advance! 🙂

**Comment by chrisblossom** [comment]
It looks like `webpack@next` has some breaking changes that need to be addressed. I'll try and look into it as soon as I have some extra time.

**Comment by alpadev** [comment]
Cheers!

I had some little vue fun project running properly on `webpack@4` and just recently updated it to use `webpack@next` and ran into a problem as well (in my case I used the default output options). So I spent some time to look into the situation and @chrisblossom you are indeed correct.

I have some experience with webpack but I'm far from being really deep into it but from what I can tell the (two) tests are failing because
1) 'removes map files' - source-maps are now nested under the toJson().assets array, within some _related_ assets array so the currentAssets isn't properly set (landed in https://github.com/webpack/webpack/pull/11254)
2) 'webpack >= 4 only › works without config' - the plugin.apply method is now called _before_ webpack fully initialized the options object passed to it, thus the plugin is getting disabled since options.output doesn't have a default value at this point. (It's a two step process landed in https://github.com/webpack/webpack/pull/10401)

https://github.com/johnagan/clean-webpack-plugin/issues/182 is also a result of this.

I think I can fix those but I'm not sure about backwards compatibility.

**Pull request closed without merging**
