### PR TITLE
Don't Accidentally delete the project's root

### PR DESCRIPTION
**Pull request by maddhruv**

### CODE REVIEW

**Comment by maddhruv** [comment]
@johnagan

**Comment by chrisblossom** [comment]
This is already built into this library via the npm package del. You can use the dangerouslyAllowCleanPatternsOutsideProject to override.

**Comment by maddhruv** [comment]
> Allow clean patterns outside of process.cwd()

it says this
but clean is by default about output.path
and i dont think this option even saves your project root

**Comment by chrisblossom** [comment]
> Allow clean patterns outside of process.cwd()
>
> it says this
> but clean is by default about output.path
> and i dont think this option even saves your project root

I don't really understand this comment.

Currently you cannot remove your project root without setting [`dangerouslyAllowCleanPatternsOutsideProject: true`](https://github.com/johnagan/clean-webpack-plugin/blob/d0e34084e20f0a0f0857d117d665f5ee8536dfa5/src/clean-webpack-plugin.ts#L305) and [`dry: false`](https://github.com/johnagan/clean-webpack-plugin/blob/d0e34084e20f0a0f0857d117d665f5ee8536dfa5/src/clean-webpack-plugin.ts#L102-L111) via [`del`](https://github.com/sindresorhus/del/blob/v5.0.0/index.js#L13-L15).

Have you had an issue with this not working?

**Comment by maddhruv** [comment]
I haven't enabled these options
but still mistakenly deleted the project's root

**Comment by chrisblossom** [comment]
> I haven't enabled these options
> but still mistakenly deleted the project's root

Can you provide the options you used to remove your project's root? I'd like to add a test case for this.

**Comment by juliantroeps** [comment]
@chrisblossom Not sure if thats the same problem, but when I set my config to an empty object like
`new CleanWebpackPlugin({}),` the build fails ([error message here](https://pastebin.com/D78yv35r)) and the whole project gets wiped.

**Pull request closed without merging**
